// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5XfwAo4ULPLJNYMPpA1oDsmV-8VjYH2U',
    appId: '1:1007416603018:android:04629192fd38039fef5873',
    messagingSenderId: '1007416603018',
    projectId: 'flutter-adabf',
    storageBucket: 'flutter-adabf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzavE26xlpXtAHUuzvOhhOdGVA_tTYfPk',
    appId: '1:1007416603018:ios:fae258f7e099f6c3ef5873',
    messagingSenderId: '1007416603018',
    projectId: 'flutter-adabf',
    storageBucket: 'flutter-adabf.appspot.com',
    iosClientId: '1007416603018-t0va9ak73n6ikhgfgvaj5imma4ili9jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
